### ISSUE TITLE
Python 3.10 compatibility

### ISSUE THREAD

**Issue by jaimergp** [BiAPoL/napari-clusters-plotter#126]
Hi folks!

Quick question: what's the reason behind this line?

https://github.com/BiAPoL/napari-clusters-plotter/blob/815ea7036758d22db085ae18869e3f9804943e63/setup.cfg#L34

We are running into this p[y310 migration issue for another package that depends on this project](https://github.com/conda-forge/morphometrics-feedstock/pull/1), where it cannot be built due to the restrictive Python pinning.

Thanks!

**Comment by haesleinhuepf** [comment]
Hi @jaimergp 

thanks for bringing this up. This was done ([git blame](https://github.com/BiAPoL/napari-clusters-plotter/commit/77a9d276fb5308cd90169a067f9b34f1e11c411c)) because of issues with [umap](https://umap-learn.readthedocs.io/en/latest/) in python 3.10.  I will send a PR because I presume the issue is resolved.

Thanks again!

Best,
Robert
