### ISSUE TITLE
HUMAP

### ISSUE THREAD

**Issue by haesleinhuepf** [BiAPoL/napari-clusters-plotter#144]
I just found the HUMAP online: https://github.com/wilsonjr/humap

Maybe it's worth a try? It's conda-installable and if it makes sense, we could add it to our list of dimensionality reduction techniques.

**Comment by lazigu** [comment]
HUMAP seems like a very interesting method. However, it requires Eigen (C++), which would make plugin's installation more complex since Eigen needs to be downloaded as a zip file and extracted in the right location, and we aim to have ncp easily installable by beginners and as part of devbio-napari.
Therefore, at least for now, this issue will be closed.
