### ISSUE TITLE
Implement plotting as heatmaps

### ISSUE THREAD

**Issue by lazigu** [BiAPoL/napari-clusters-plotter#148]
For some use cases, where data contains a lot of points, it would be nice to have a checkbox "display the plot as a heatmap". 
A challenge is to still retain the information where each point in the plot is in the label image.

**Comment by haesleinhuepf** [comment]
Also consider talking to @stefanhahmann , he's implementing something similar in Java these days 🚀

**Comment by stefanhahmann** [comment]
We were actually thinking of a different approach for the same problem (to many points in the plot) for a point plotter in the Fiji-Plugin Mastodon: https://github.com/mastodon-sc/mastodon

For this, we had the idea to do a density based clustering of the points (e.g. with DBSCAN algorithm) and just show the cluster centers scaled to the amount of points they represent. There is a similar method that I know when it comes to showing many point features on a map.

![grafik](https://user-images.githubusercontent.com/10515534/206465193-7c7cb438-5817-4138-a04b-2668509ff05b.png)

But I also very much like the idea of a heat map (or "kernel density estimation" as one might call it more scientifically) to represent dense point areas. Might be even more intuitive. The original points would need to stay in the RAM in both cases in order to be able to make selections.

**Comment by zoccoler** [comment]
> The original points would need to stay in the RAM in both cases in order to be able to make selections.
That's exactly what @lazigu and I were discussing today. We thought maybe plots like these could be enabled/disabled by the user and be like a "mask" on top. That way, the user could select clusters on the heatmaps but the code would look for points in the original plot. What do you think?

**Comment by stefanhahmann** [comment]
Sounds good.
Heat map mask could look like this:

![grafik](https://user-images.githubusercontent.com/10515534/206470065-ec326de6-a972-445a-83c4-4343287eedb5.png)

**Comment by haesleinhuepf** [comment]
I'm getting @allysonryan in the loop here, because she obviously did similar things recently. :-)

**Comment by thorstenwagner** [comment]
I just made a implementation using 2D histograms ( #196 ). Maybe this is already enough?
