### ISSUE TITLE
Napari crashes when calling dimensionality reduction from notebook

### ISSUE THREAD

**Issue by haesleinhuepf** [BiAPoL/napari-clusters-plotter#169]
I just met the issue with @marabuuu and saw it earlier on my PC as well: Napari crashes (and the Jupyter kernel dies) when opening Napari from a Jupyter notebook and then calling dimensionality reduction (UMAP) from the menu.

How to reproduce:
* Open napari from a Jupyter notebook
* Load a dataset (we used 3D+t)
* Load a segmentation
* Do measurements (We used Tools > Measurement Tables > Measurement of all Frames (simpleitk)
* Run menu Tools > Measurements > Dimensionality reduction (ncp)
* Choose UMAP and click on run. 

After a while, napari will just close and an error shows up that the Jupyter kernel has died. This kind of error hints to a segmenation fault. When doing the same thing from napari that was started from the command line, it works fine.

**Comment by haesleinhuepf** [comment]
Thanks for diving into this @lazigu ! 🤩

> * Higher versions of ncp have multithreading implemented, therefore, this means the issue lies there.

Very good analysis! And yes, we should disable multi-threading ...

> Any ideas, on what to try next?
> I would prefer fixing it without removing multithreading, which is a solution in the worst case.

... and after releasing a version without multi-threading we could try out alternative approaches on git branches. Highest goal should be preventing hard crashes. Making it nice and user-friendly are secondary goals 😉

**Comment by lazigu** [comment]
Forgot to mention, that this issue happens only for UMAP, and not t-sne or PCA, and not for any clustering algorithms.

So the easiest way would be to disable multithreading only for UMAP, it would not require any big code reorganisation. Maybe I could even leave the multithreaded function as an optional selection via a checkbox under the advanced options menu, which by default would be off? 

I am also not sure whether I should open an issue at the UMAP repository or numba because it is hard to describe the issue because we don't get any error message.

@haesleinhuepf waiting for your opinion again :)

By the way, thanks a lot to @marabuuu for the help in debugging this!

**Comment by haesleinhuepf** [comment]
> So the easiest way would be to disable multithreading only for UMAP, it would not require any big code reorganisation. Maybe I could even leave the multithreaded function as an optional selection via a checkbox under the advanced options menu, which by default would be off?

Yes, that sounds great!
