### ISSUE TITLE
Matplotlib 3.7.0 incompatible

### ISSUE THREAD

**Issue by kevinyamauchi** [BiAPoL/napari-clusters-plotter#176]
Hello! I am teaching a course and we are using the `napari-clusters-plotter` plugin. I think matplotlib introduced a breaking change in their 3.7.0 release that causes an issue with the plotter widget. When the students launched the plotter widget with matplotlib=3.7.0 installed, the received a keyword argument error.

**Comment by lazigu** [comment]
Thank you so much for reporting this @kevinyamauchi! I will take a look

**Comment by lazigu** [comment]
@kevinyamauchi, it appears to be that the issue was already fixed on the main branch (it was caught by our tests a couple of days ago), but the new release was not made yet, sorry about that! With the latest version (0.6.1) the issue should be gone. 
Thanks for using the plugin, and please let us know if there are more issues that your students encounter :)
