### ISSUE TITLE
Make widgets available via public API

### ISSUE THREAD

**Issue by haesleinhuepf** [BiAPoL/napari-clusters-plotter#178]
I sometimes write notebooks where I do measurements and open a napari viewer. It would be great if we could open the plotter from code as well. Usually, I do this using this code importing a private member:

```
from napari_clusters_plotter._dock_widget import PlotterWidget
```

If `PlotterWidget` and the other main widgets were imported [in the `__init__.py`](https://github.com/BiAPoL/napari-clusters-plotter/blob/8a5acb72dd6e9866dd26e1335ecc4b31e1693f8b/napari_clusters_plotter/__init__.py#L3), they could be accessed like this:
```
from napari_clusters_plotter import PlotterWidget
```

Is there anything that speaks agains this? (-:

**Comment by haesleinhuepf** [comment]
If this was done, we should update the notebooks here:
https://github.com/BiAPoL/napari-clusters-plotter-example-notebooks/blob/main/notebooks/

**Comment by lazigu** [comment]
Alternatively, the plotter can be opened this way without importing a private member :)

![image](https://user-images.githubusercontent.com/52177660/220126011-8eca171f-d524-4253-a2eb-9ea2c16abdfb.png)

or this way:

![image](https://user-images.githubusercontent.com/52177660/220128137-4a16aad9-4845-4ac7-ac70-0d632f2cb8e5.png)

Otherwise, I am really not sure if anything speaks against adding a proposed line, I think you @haesleinhuepf would know more about this :)
I tested it, and it seems that the plugin is imported normally and all tests pass.

**Comment by haesleinhuepf** [comment]
Yeah, importing Widgets in __init__.py is a common thing. May I send a PR or do you aleady have it on a branch @lazigu ?

**Comment by lazigu** [comment]
I have it so I will create a PR now :)
