### ISSUE TITLE
Simplify `button()` and `title()` Qt code

### ISSUE THREAD

**Issue by haesleinhuepf** [BiAPoL/napari-clusters-plotter#180]
I'm wondering if this code [here](https://github.com/BiAPoL/napari-clusters-plotter/blob/8a5acb72dd6e9866dd26e1335ecc4b31e1693f8b/napari_clusters_plotter/_Qt_code.py#L139-L144):

```
def button(name):
    widget = QWidget()
    widget.setLayout(QHBoxLayout())
    button = QPushButton(name)
    widget.layout().addWidget(button)
    return widget, button
```

could be simplified to:
```
def button(name):
    button = QPushButton(name)
    return button, button
```

We need to return button twice to be backwards compatible internally. Alternatively, could replace calls to `button(name)` by  `QPushButton(name)`. 

Analogously, we could update `title()` code [here](https://github.com/BiAPoL/napari-clusters-plotter/blob/8a5acb72dd6e9866dd26e1335ecc4b31e1693f8b/napari_clusters_plotter/_Qt_code.py#L65).

Is there anything that speaks against this?

**Comment by lazigu** [comment]
Hi @haesleinhuepf,

The button needs to be added to a container for the code to set spacing downstream to work, otherwise, such an error is received:
```
File c:\users\zigut\projects\napari-clusters-plotter\napari_clusters_plotter\_plotter.py:152, in PlotterWidget.__init__(self=<napari_clusters_plotter._plotter.PlotterWidget object>, napari_viewer=Viewer(axes=Axes(visible=False, labels=True, col...._transform_active_layer at 0x0000021C10A81090>}))
    150 for i in range(self.layout().count()):
    151     item = self.layout().itemAt(i).widget()
--> 152     item.layout().setSpacing(0)
        item = <PyQt5.QtWidgets.QPushButton object at 0x0000021C1B52AC20>
    153     item.layout().setContentsMargins(3, 3, 3, 3)
    155 # adding spacing between fields for selecting two axes

AttributeError: 'NoneType' object has no attribute 'setSpacing'
```

If we skip changing the spacing for buttons it looks a bit weird in my opinion, that is why I added buttons to separate containers:
![image](https://user-images.githubusercontent.com/52177660/220088581-680da6df-b481-4602-81ce-72844bdc70f8.png)

Maybe spacing could be changed in some other way, however, if at some point we have a Qt Designer file for all the visual stuff, perhaps it is not necessary to delve into this now :)

**Comment by haesleinhuepf** [comment]
Ahhhh, that's why! Thanks @lazigu ! I learned something 🙌
