### ISSUE TITLE
Allow usage of sub samples for Measurment -> Plot 

### ISSUE THREAD

**Issue by thorstenwagner** [BiAPoL/napari-clusters-plotter#191]
This issue is a sub-issue of #189 : 

It would probably  make sense, to allow the user to only use a subsample for plotting, but applying the lasso region to the complete dataset. That would probably also make the plotting much faster, which is right now very slow.  Additionally, it would reduce the overplotting.

I can do the implementation, just want to discuss this with you before starting. What do you think? What would be the way you would like to see it implemented?

**Comment by lazigu** [comment]
I can imagine the selection for subsampling living under a collapsible widget "advanced options" (e.g. like in the dimensionality reduction widget when umap is selected, picture below). When the user expands it, it would contain the selection parameter _n_, specifying every _n_ th data point that will be plotted. I would put there other plotting parameters later also, together with the checkbox to consider not selected data points as noise/background instead of the second cluster.

This way the UI does not change at all for users that are not interested in these features. What do you think?

![image](https://user-images.githubusercontent.com/52177660/223428236-f71e49ec-f66b-4224-afb1-9d6c0aa28f67.png)

**Comment by thorstenwagner** [comment]
@thorstenwagner @lazigu 

I think this issue can be closed. From my side, the speed with the new 2D histogram is good enough to display also large datasets.

Please close it if you think the same.
