### ISSUE TITLE
Call plotter from external plugin

### ISSUE THREAD

**Issue by thorstenwagner** [BiAPoL/napari-clusters-plotter#198]
I try to call the Plotter from an external plugin, here is how I do it:

```python
umap = pd.read_pickle(filename)
    if "label" not in umap.keys().tolist():
        label_column = pd.DataFrame(
            {"label": np.array(range(1, (len(umap) + 1)))}
        )
        umap = pd.concat([label_column, umap], axis=1)

    if hasattr(label_layer, "properties"):
        label_layer.properties = umap
    if hasattr(label_layer, "features"):
        label_layer.features = umap

    viewer = napari.current_viewer()
    widget, plotter_widget = viewer.window.add_plugin_dock_widget('napari-clusters-plotter', widget_name='Plotter Widget')
    plotter_widget.plot_x_axis.setCurrentIndex(1)
    plotter_widget.plot_y_axis.setCurrentIndex(2)

    plotter_widget.bin_auto.setChecked(True)
    plotter_widget.plotting_type.setCurrentIndex(1)
    plotter_widget.plot_hide_non_selected.setChecked(True)
    plotter_widget.run(
                umap,
                "umap_0",
                "umap_1",
                plot_cluster_name=None,
            )
```

However, that only works if I remove the following lines of the _plotter.py:
https://github.com/BiAPoL/napari-clusters-plotter/blob/b83922faa77af2f48d417887955dc30e3a3214dc/napari_clusters_plotter/_plotter.py#L293-L295

Question, shall we remove it? :-)

**Comment by haesleinhuepf** [comment]
We need to test this carefully. I implemented this line because in Napari, you can hide dock-widgets. In case the user interacts with data invoking a re-draw, this would cost computational bandwidth if invisible plots are drawn in the background. If I remember correctly, the use-case was that the user selected an object in the label image and then the plot was drawn with this one data point highlighted. We should check if the drawing is still executed in case the user clicks in the label image to select objects. If this is no longer part of the functionality, the two lines above can be removed.

**Comment by lazigu** [comment]
> We should check if the drawing is still executed in case the user clicks in the label image to select objects. If this is no longer part of the functionality, the two lines above can be removed.

This functionality was removed in https://github.com/BiAPoL/napari-clusters-plotter/pull/80, but there was a request to bring it back in this issue #189. 


> I tried, run is not called when you click in the labels layer. Alternatively, we could also add a "force_redraw=False" default argument to `run(..)` and change those lines to:
> 
> ```
> if not self.isVisible() and force_redraw==False: 
>      # don't redraw in case the plot is invisible anyway 
>      return 
> ```

I think I would be in favour of this solution if we are thinking about bringing the previously mentioned functionality back.
