### ISSUE TITLE
Manual cluster selection after zooming in plot

### ISSUE THREAD

**Issue by Cryaaa** [BiAPoL/napari-clusters-plotter#28]
When I zoom in on the plot I cannot get back to the lasso selector for selecting manual clusters. I guess a button for that would be useful or that it reverts back to it automatically after zooming in.

**Comment by zoccoler** [comment]
Hi @Cryaaa,

I was able to get back the lasso tool after zooming if I click again on the zoom button. I think this is the default usage of the matplotlib toolbar, being the 'zoom' and 'pan' buttons more like a toggle-button rather than a pushbutton.

We can either leave it like this and put in the documentation or override this behavior similar to what we did to the 'save' button. Which do you guys prefer?

**Comment by Cryaaa** [comment]
Hi @zoccoler 
Ahhhhh I didn't even think to do that for some reason :D. I think it should be mentioned somewhere definitely! I don't know if its difficult to implement but maybe if you hover above the zoom icon it could be mentioned? Otherwise the documentation would be enough.

**Comment by lazigu** [comment]
I think to mention it in the documentation would be enough in case somebody else runs into the same issue.
