### ISSUE TITLE
Test current version before releasing

### ISSUE THREAD

**Issue by haesleinhuepf** [BiAPoL/napari-clusters-plotter#302]
I'm not sure if all use cases were properly tested. It would be cool if someone volunteers for testing them before #281 , as the tool is downloaded and used by quite some folks.

* [x] 2D labels
* [x] 3D labels
* [x] 2D + time
* [x] 3D + time
* [x] points
* [x] surface
* [x] points + time ?  (bf09d794596de073a993f5e8c942782bb1a42ff3)
* [x] surface + time ?  (9cf67049d4222163e2f9c08f4c46778eddb52729)

For the last tests, example data might be necessary (see also #301 )

Thanks!

**Comment by Cryaaa** [comment]
I had made some progress on this issue but one Issue is that the [napari-skimage-regionprops](https://github.com/haesleinhuepf/napari-skimage-regionprops) function `show_table` is incompatible with surface layers currently. I have made a suggestion to fix it as a [PR](https://github.com/haesleinhuepf/napari-skimage-regionprops/pull/85) but until this gets merged and released we will need to either keep the newest cluster plotter release on hold or find a workaround for showing the table..

**Comment by Cryaaa** [comment]
@zoccoler Have you tested the new features manually yet? I don't think the plugin will work for the surface layer as expected because as soon as you perform dimension reduction or clustering on the surface layer the `show_table` function will erase the surface layer data.... I don't know if you would prefer just to do a workaround which I could get started on or if we should wait until the suggested PR is merged in napari-skimage-regionprops?

**Comment by zoccoler** [comment]
Hi @Cryaaa ,

I tried to fix [that PR](https://github.com/haesleinhuepf/napari-skimage-regionprops/pull/85) today, but I did not try that branch with the napari-clusters-plotter.
If you have some time, could you test if it would work?
