### ISSUE TITLE
Progress bar for k-Means clustering and friends

### ISSUE THREAD

**Issue by haesleinhuepf** [BiAPoL/napari-clusters-plotter#36]
Hi all,

Fabrice Senger had a good idea for improving ncp: A progress bar for the operations that take a long time:
https://forum.image.sc/t/dont-yet-support-nd-fancy-indexing/61878/2

There's something about this in the napari documentation:
https://napari.org/docs/dev/api/napari.utils.progress.html

Happy to have a chat about that request. It's not urgent btw. but I think nice-to-have. :-)

Best,
Robert

**Comment by lazigu** [comment]
Hi @haesleinhuepf,

I actually also had this idea, but because for me napari usually stops responding even during not demanding tasks, and 'comes back to life' soon, I gave up on the idea :D
But I understand that for other users it would be great to have this implemented so I will try!

Best wishes,
Laura
