### ISSUE TITLE
set matplotlib backend locally?

### ISSUE THREAD

**Issue by kevinyamauchi** [BiAPoL/napari-clusters-plotter#76]
Hello! Thanks for the great library. I am trying to use `napari-clusters-plotter` as the plotting library for a measurement library. I've noticed that after plotting data using `napari-clusters-plotter` in a napari viewer launched from a jupyter notebook, the matplotlib plots executed in the notebook are no longer plotted in the notebook (i.e., "inline") and are instead plotted in qt widgets. I am not a matplotlib expert, but I believe it is because the backend is being set globally (see line below). Is it possible to set the backend more locally (i.e., just for plots generated by this library)?

https://github.com/BiAPoL/napari-clusters-plotter/blob/d8af60a73a90f8b1383b8aba2f39b4e8895d532b/napari_clusters_plotter/_plotter.py#L36

To reproduce:
1. launch napari from a jupyter notebook
2. open the `napari-clusters-plotter` plugin and plot some features
3. go back to the notebook and create a plot with matplotlib
4. The resulting plot is displayed in a "pop up" qt widget

**Comment by jo-mueller** [comment]
Hey @kevinyamauchi @Cryaaa ,

this is a good point! The plotting backend is indeed set globally [here](https://github.com/BiAPoL/napari-clusters-plotter/blob/4e17608fbfe82c152c0c638aaf0ca89335ca22ee/napari_clusters_plotter/_plotter.py#L36). Would changing this to `inline` directly put the plot into a noteboook? If so, we could surely declare the backend within the scope of the Plotting Widget.

Anothher option I could think of, would be to make the plotting functions and the widget independent from each other. Currently, the plotting functions are implemented as 

```Python
class Plotter():
  def plot_something(self, data):
```

We could re-arrange this to 

```Python
class Plotter():
  # create canvas and stuff here

def plot_something(ax, data):
  # do the plotting
```

When the plotting functions are called from, i.e., other plugins, the `ax` argument could point to a created plot widget - but also to a matplotlib figure instance in a notebook. Would this work? I guess the backend would still have to be selected anyway 🤔

**Comment by zoccoler** [comment]
Hi @kevinyamauchi @Cryaaa @jo-mueller,

From my understanding, when you open a napari viewer from a jupyter notebook, the backend is changed to qt at that point, so I am not sure that the line mentioned would be what is causing the problem. You could check the current backend with `matplotlib.get_backend()`. In fact, I commented that line out and this still happens.

What is weird to me is that, if you plot something in the notebook, and open napari after that (and do whatever there), the backend changes to qt5Agg, but you still get plots 'inline'. However, if you open the viewer first and then try to plot, you get a separate window... Can anyone replicate this?

A workaround would be to [change the backend](https://matplotlib.org/stable/users/explain/backends.html#selecting-a-backend) around the plot, something like this:
```
%matplotlib inline
plt.plot(x,y) 
plt.show()
%matplotlib qt
```
Not very pretty, but it seems to work. qt has to come back otherwise napari of course crashes.

Separating the function from the class as @jo-mueller said could be a way to use it outside. I am also not sure yet how to pass all the necessary parameters and if that is what you need. Are you planning to get the data from the widget and plot them again in the notebook? Or do you want to get the full Plotter class and use it somewhere else?

This is a great discussion btw :)

**Comment by kevinyamauchi** [comment]
Hey everyone. Thanks for the quick feedback!

Here's a small notebook I created to reproduce the issue: https://gist.github.com/kevinyamauchi/da344a35176ed9003aefc8a720fa4874

<details>
  <summary>Environment details</summary>
Environment:
napari: 0.4.15
Platform: macOS-10.15.7-x86_64-i386-64bit
System: MacOS 10.15.7
Python: 3.8.13 (default, Mar 28 2022, 06:16:26) [Clang 12.0.0 ]
Qt: 5.15.2
PyQt5: 5.15.6
matplotlib: 3.5.1
NumPy: 1.21.6
notebook: 6.4.10
SciPy: 1.8.0
Dask: 2022.04.0
VisPy: 0.9.6

OpenGL:
- GL version: 2.1 INTEL-14.7.20
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1440x900, scale 2.0

Plugins:
- console: 0.0.4
- napari-clusters-plotter: 0.3.0
- scikit-image: 0.4.15
- svg: 0.1.6
</details>


> What is weird to me is that, if you plot something in the notebook, and open napari after that (and do whatever there), the backend changes to qt5Agg, but you still get plots 'inline'. However, if you open the viewer first and then try to plot, you get a separate window... Can anyone replicate this?

I get very similar behavior. Using the example above, if I make a plot in the notebook before instantiating the viewer, I get inline plots.
<img width="1508" alt="Screenshot 2022-04-13 at 10 18 17" src="https://user-images.githubusercontent.com/1120672/163132716-bd97f619-f3a4-41ec-95c9-f6e4b604ba03.png">

However, I also get a blank popup window 😛 
<img width="1370" alt="Screenshot 2022-04-13 at 10 18 10" src="https://user-images.githubusercontent.com/1120672/163132688-c34e05f1-3c86-4f02-b1d7-fa1966262028.png">


> In fact, I commented that line out and this still happens.

Interesting. Do you think it's possible a dependency of `napari-clusters-plotter` could setting the backend as well?

**Comment by zoccoler** [comment]
> Interesting. Do you think it's possible a dependency of napari-clusters-plotter could setting the backend as well?

I did some more testing, and it might have been another plugin I had installed in the same environment which was setting the backend in a similar way...

In a clean environment, if [that line](https://github.com/BiAPoL/napari-clusters-plotter/blob/d8af60a73a90f8b1383b8aba2f39b4e8895d532b/napari_clusters_plotter/_plotter.py#L36) is deleted, it appears to fix this.

@jo-mueller,  @Cryaaa and I were discussing this today and @Cryaaa will test this change and likely create a PR for this.

**Comment by kevinyamauchi** [comment]
Awesome. Thanks, everyone!

**Comment by Cryaaa** [comment]
@kevinyamauchi 
The main branch was now updated so that this dependancy is removed! I guess it will be some time until this change makes it into the next release but maybe you can check it for yourself! This manual setting of the backend could also be present in some other plugins though just as a warning (we are in the process of removing it from our other plugins at the moment). 

And if you are interested in any of the code we would be happy to chat :) 

Have a nice easter!

**Comment by kevinyamauchi** [comment]
Awesome. Thanks! I will give it a go this week!
